_target_: iris.src.models.tokenizer.tokenizer.Tokenizer

vocab_size: 2048
embed_dim: 512
encoder:
  _target_: iris.src.models.tokenizer.nets.Encoder
  config:
    _target_: iris.src.models.tokenizer.nets.EncoderDecoderConfig
    resolution: 64
    in_channels: 3
    z_channels: 512
    ch: 64
    ch_mult: [1, 1, 1, 1, 1] # changed from [1, 1, 1, 1, 1]
    num_res_blocks: 2
    attn_resolutions: [8, 16]
    out_ch: 3
    dropout: 0.0
decoder:
  _target_: iris.src.models.tokenizer.nets.Decoder
  config: ${..encoder.config}